- name: Create application directory
  file:
    state: directory
    path: /opt/pas/azure-nagios
    owner: root
    group: root
    mode: "0755"
  become: yes

- name: Copy application files
  copy:
    src: "{{ role_path }}/../../../js/"
    dest: /opt/pas/azure-nagios
    owner: root
    group: nagios
    mode: "0755"
  notify: Install packages
  become: yes
